#+TITLE: Simple Domain Modeling Language
#+SUBTITLE: Language Error Codes
#+AUTHOR: Simon Johnston
#+EMAIL: johnstonskj@gmail.com
#+LANGUAGE: en
#+STARTUP: overview hidestars inlineimages entitiespretty
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../rtd-sdml.css"/>
#+OPTIONS: toc:3


#+BEGIN_SRC emacs-lisp :exports none
(require 'ebnf-mode)
(require 'ob-rust)
(require 'ob-sdml)
#+END_SRC

This page provides a reference to the errors, warnings, and informational messages defined in the =sdml_error= crate and
output by the =sdml= command-line tool.

* Bugs

This category represents bugs in the command-line tool where it's parser receives unexpected nodes from the underlyiung
tree-sitter parser.

** B01: Tree-Sitter Error Node
:PROPERTIES:
:CUSTOM_ID: B0001
:END:

If the tree-sitter parser itself cannot parse some content it inserts an =error= node in the tree. When the SDML parser
encounters such a node it is clearly a defect in the underlying source, but we don't yet know what.

The =Diagnostic= for this error will attempt to record the file ID, location, and the name of any rule the parser was
processing when the error node was found.

** B02: Tree-Sitter Unexpected Node
:PROPERTIES:
:CUSTOM_ID: B0002
:END:

The =Diagnostic= for this error will attempt to record the file ID, location, and the name of any expected nodes along
with the name of the node found.

** B03: Tree-Sitter Missing Node
:PROPERTIES:
:CUSTOM_ID: B0003
:END:

The =Diagnostic= for this error will attempt to record the file ID, location, and the name of any expected nodes along
with the name of any variable that might have contained the expected node.

** B03: Tree-Sitter Missing Variable
:PROPERTIES:
:CUSTOM_ID: B0004
:END:

The =Diagnostic= for this error will attempt to record the file ID, location, and the name of the expected variable along
with the name of the node kind that should have contained the expected variable.


* Errors

** E101: ModuleNotFound
:PROPERTIES:
:CUSTOM_ID: E0101
:END:

TBD

*** Example

#+BEGIN_SRC sdml :exports code :eval never
module example <https://example.com/api> is

  import owl <http://www.w3.org/2002/07/owl#>

end
#+END_SRC

#+BEGIN_EXAMPLE
error[E0101]: imported module `owl` has no version URI
  ┌─ examples/simple.sdm:5:5
  │
5 │     owl <http://www.w3.org/2002/07/owl#>
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this import requires a version URI
  │
  = for more details, see <https://sdml.io/errors/#E0101>
#+END_EXAMPLE

** E102: ModuleVersionNotFound
:PROPERTIES:
:CUSTOM_ID: E0102
:END:

TBD

** E103: ModuleVersionMismatch
:PROPERTIES:
:CUSTOM_ID: E0103
:END:

TBD

** E104: DuplicateDefinitionName
:PROPERTIES:
:CUSTOM_ID: E0104
:END:

TBD

** E105: DuplicateMemberName
:PROPERTIES:
:CUSTOM_ID: E0105
:END:

TBD

** E106: DuplicateVariantName
:PROPERTIES:
:CUSTOM_ID: E0106
:END:

TBD

** E107: InvalidIdentifier
:PROPERTIES:
:CUSTOM_ID: E0107
:END:

TBD

** E108: InvalidLanguageTag
:PROPERTIES:
:CUSTOM_ID: E0108
:END:

TBD

** E109: InvalidValueForType
:PROPERTIES:
:CUSTOM_ID: E0109
:END:

TBD

** E110: InvalidModuleBaseUrl
:PROPERTIES:
:CUSTOM_ID: E0110
:END:

TBD

** E111: InvalidModuleVersionInfo
:PROPERTIES:
:CUSTOM_ID: E0111
:END:

TBD

** E112: InvalidModuleVersionUrl
:PROPERTIES:
:CUSTOM_ID: E0112
:END:

TBD

** E113: DefinitionNotFound
:PROPERTIES:
:CUSTOM_ID: E0113
:END:

TBD


* Warnings

** W301: ModuleAlreadyImported
:PROPERTIES:
:CUSTOM_ID: W0301:
:END:

An import statement includes a module already imported.

*** Example

#+BEGIN_SRC sdml :exports code :eval never
module example <https://example.com/api> is

  import owl

  import [ dc xsd owl owl ]

end
#+END_SRC

#+BEGIN_EXAMPLE
warning[W0301]: duplicate import of module
  ┌─ examples/errors/W0301.sdm:5:19
  │
3 │   import owl
  │          --- was previously imported here
4 │ 
5 │   import [ dc xsd owl owl ]
  │                   ^^^ this module
  │
  = for more details, see <https://sdml.io/errors/#W0301>

warning[W0301]: duplicate import of module
  ┌─ examples/errors/W0301.sdm:5:23
  │
3 │   import owl
  │          --- was previously imported here
4 │ 
5 │   import [ dc xsd owl owl ]
  │                       ^^^ this module
  │
  = for more details, see <https://sdml.io/errors/#W0301>

warning: module `example` generated 2 warnings.
#+END_EXAMPLE

** W302: MemberAlreadyImported
:PROPERTIES:
:CUSTOM_ID: W0302
:END:

An import statement includes a member already imported.

*** Example

#+BEGIN_SRC sdml :exports code :eval never
module example <https://example.com/api> is

  import owl:Class

  import [ dc xsd owl:Class ]

end
#+END_SRC

#+BEGIN_EXAMPLE
warning[W0302]: duplicate import of member
  ┌─ examples/errors/W0302.sdm:5:19
  │
3 │   import owl:Class
  │          --------- was previously imported here
4 │ 
5 │   import [ dc xsd owl:Class ]
  │                   ^^^^^^^^^ this member
  │
  = for more details, see <https://sdml.io/errors/#W0302>

warning: module `example` generated 1 warnings.
#+END_EXAMPLE

** W303: ValidationIncomplete
:PROPERTIES:
:CUSTOM_ID: W0303
:END:

TBD


* Informational

** I501: IncompleteDefinition
:PROPERTIES:
:CUSTOM_ID: I0501:
:END:

TBD

** I502: IncompleteMember
:PROPERTIES:
:CUSTOM_ID: I0502
:END:

TBD

** I503: StringWithoutLanguage
:PROPERTIES:
:CUSTOM_ID: I0503
:END:

TBD

** I504: UnconstrainedDatatype
:PROPERTIES:
:CUSTOM_ID: I0504
:END:

TBD


* Appendix: Rust =ErrorCode= enum

#+BEGIN_EXAMPLE rust 
pub enum ErrorCode {
    // ---------------------------------
    // Bugs
    // ---------------------------------
    TreeSitterErrorNode = 1,
    TreeSitterUnexpectedNode = 2,
    TreeSitterMissingNode = 3,
    TreeSitterMissingVariable = 4,

    // ---------------------------------
    // Errors
    // ---------------------------------
    ModuleNotFound = 101,
    ModuleVersionNotFound = 102,
    ModuleVersionMismatch = 103,
    DuplicateDefinitionName = 104,
    DuplicateMemberName = 105,
    DuplicateVariantName = 106,
    InvalidIdentifier = 107,
    InvalidLanguageTag = 108,
    InvalidValueForType = 109,
    InvalidModuleBaseUrl = 110,
    InvalidModuleVersionInfo = 111,
    InvalidModuleVersionUrl = 112,
    DefinitionNotFound = 113,

    // ---------------------------------
    // Warnings
    // ---------------------------------
    ModuleAlreadyImported = 301,
    MemberAlreadyImported = 302,
    ValidationIncomplete = 303,

    // ---------------------------------
    // Informational
    // ---------------------------------
    IncompleteDefinition = 501,
    IncompleteMember = 502,
    StringWithoutLanguage = 503,
    UnconstrainedDatatype = 504,
}
#+END_EXAMPLE
